### ISSUE TITLE
TINCR XDLRC creating pips that don't exist in ISE XDLRC 

### ISSUE THREAD

**Issue by ttown523** [bradselw/tincr#17] opened 2016-03-03 00:12 UTC
Hi Brad,

It looks like we may have found a bug in the XDLRC that TINCR is producing. 
**Part**: xc7a100tcsg324
**Tile**: INT_INTERFACE_R_X1Y54

For the above part and tile, it appears that the TINCR generated XDLRC file has several pip connections that don't exist in the ISE generated XDLRC. One example of this can be seen below. 

**Example**:  (pip INT_INTERFACE_R_X1Y54 INT_INTERFACE_IMUX29 -> INT_INTERFACE_LOGIC_OUTS2)

Routers that use this connection and import the routing information back into Vivado are failing because the connection does not actually exist. I have attached two files to help debug this. The first is the XDLRC generated from TINCR for the tile, and the second is the XDLRC generated from ISE.

[int_interfacex1y54_tincr.txt](https://github.com/bradselw/tincr/files/155930/int_interfacex1y54_tincr.txt)
[int_interfacex1y54_ise.txt](https://github.com/bradselw/tincr/files/155933/int_interfacex1y54_ise.txt)

 Can you take a look at this? Thanks.

**Comment by nelsobe** [comment] 2016-03-03 01:03
Just to clarify, Thomas, the problem is that the PIP really doesn’t exist in Vivado?

The reason I ask is we know there are wire differences between ISE’s XDLRC and VIvado’s (thanks to Brad’s MS work).  But, you said the pip didn’t exist in ISE generated XDLRC.

If this PIP also doesn’t exist in the Vivado device model then we do have a problem.

Prof Nelson

**Comment by ttown523** [comment] 2016-03-03 01:19
So it looks like I found the bug. In your original xdlrc.tcl, on line 295, you had:

`set pips [lsort [get_pips -quiet -of_object $tile -filter !IS_TEST_PIP]]`

However, you also need to filter out the excluded pips:

`set pips [lsort [get_pips -quiet -of_object $tile -filter {!IS_TEST_PIP && !IS_EXCLUDED_PIP}]]`

This looks like it fixed the problem of adding pips that don't exist in the ISE version of XDLRC.  After this change, I now notice that there are a few pips missing from the TINCR XDLRC. The two attached files demonstrate this (I only included the pips this time). 

[pips_tincr.txt](https://github.com/bradselw/tincr/files/155987/pips_tincr.txt)
[pips_ise.txt](https://github.com/bradselw/tincr/files/155988/pips_ise.txt)

However, when I change the following lines of code (lines 297-298):

`set uphill_node [get_nodes -quiet -uphill -of_object $pip]`
`set downhill_node [get_nodes -quiet -downhill -of_object $pip]`  

to: 

`set uphill_node [get_wires -quiet -uphill -of_object $pip]`
`set downhill_node [get_wires -quiet -downhill -of_object $pip]`  

All of the pips now show up. I am assuming that since we can't find any uphill nodes attached to the pip, this implies that the pips don't have drivers and we can safely leave them out of the XDLRC. Therefore, I think it is best to stick to the "get_nodes" version. Do you agree Brad? If you do, then I will submit another pull request with the updates.

**Comment by ttown523** [comment] 2016-03-03 01:25
Dr. Nelson,

It appears that the pip does exist in Vivado, but is marked as "Excluded." I am not sure exactly what this means, all I know is that we cannot generate valid routes in Vivado if we use the pip. So we shouldn't include it in the XDLRC. Brad probably knows more about this then I do.

**Comment by bradselw** [comment] 2016-03-04 23:02
Thanks for posting an issue. I'll take a look at this over the weekend.

**Comment by bswwhite** [comment] 2016-03-05 06:12
Took a look at this and ttown523 is right - the XDLRC produced by Tincr should not include excluded PIPs. Out of the 145,200 excluded PIP objects in the xc7a100t, none of them map to actual components on the device. Good catch!

As nelsobe pointed out, Tincr XDLRCs are not meant to have a one-to-one correlation with ISE XDLRCs. This is for a number of reasons, pointed out in my thesis. To summarize, Tincr's XDLRC is a super-set of ISE's XDLRC that has been trimmed. By trimmed, I mean that components which really serve no functional purpose are excluded from Tincr's XDLRC. This is what is happening on lines 297-8: PIPs that don't have either a source or sink node are just floating (even if Vivado reports that there is a wire object there). So yes, it's best to stick with the "get_nodes" version.

I am creating a pull request to exclude these phony PIPs.

**Comment by bradselw** [comment] 2016-04-12 01:26
Merged PR to exclude "excluded" PIPs from XDLRC

**Closed as completed by bradselw** 2016-04-12 01:26 UTC
Labels: bug
